import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";

export const metadata: Metadata = {
  title: "Next auth project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {

  return (

    <html lang="en">

      <body>
      {/* providers */}

        <Providers>

          {children}

        </Providers>

      </body>


    </html>

  );

};